/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_hdrcamera_ImageUtils */

#ifndef _Included_com_example_hdrcamera_ImageUtils
#define _Included_com_example_hdrcamera_ImageUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_hdrcamera_ImageUtils
 * Method:    convertYUV420ToRGBA8888
 * Signature: ([B[B[B[IIIIIIZ)V
 */
JNIEXPORT void JNICALL Java_com_example_hdrcamera_ImageUtils_convertYUV420ToARGB8888
  (JNIEnv *, jobject, jbyteArray, jbyteArray, jbyteArray, jintArray, jint, jint, jint, jint, jint, jboolean);

#ifdef __cplusplus
}
#endif
#endif
