/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_hdrimg2_HDRRenderer */

#ifndef _Included_com_example_hdrimg2_HDRRenderer
#define _Included_com_example_hdrimg2_HDRRenderer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_hdrimg2_HDRRenderer
 * Method:    init
 * Signature: (IIIIII)V
 */
JNIEXPORT void JNICALL Java_com_example_hdrimg2_HDRRenderer_init
  (JNIEnv *, jobject, jint, jint, jint, jint, jint, jstring, jint);

/*
 * Class:     com_example_hdrimg2_HDRRenderer
 * Method:    upLoadImg
 * Signature: (Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_com_example_hdrimg2_HDRRenderer_upLoadImg
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     com_example_hdrimg2_HDRRenderer
 * Method:    render
 * Signature: ([FII)[I
 */
JNIEXPORT jintArray JNICALL Java_com_example_hdrimg2_HDRRenderer_render
  (JNIEnv *, jobject, jfloatArray, jint, jint);

/*
 * Class:     com_example_hdrimg2_HDRRenderer
 * Method:    freeCurrentState
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_hdrimg2_HDRRenderer_freeCurrentState
  (JNIEnv *, jobject);

/*
 * Class:     com_example_hdrimg2_HDRRenderer
 * Method:    getSmallImage
 * Signature: (Ljava/lang/String;I)[F
 */
JNIEXPORT jfloatArray JNICALL Java_com_example_hdrimg2_HDRRenderer_getSmallImage
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     com_example_hdrimg2_HDRRenderer
 * Method:    clearTime
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_hdrimg2_HDRRenderer_clearTime
  (JNIEnv *, jobject);

/*
 * Class:     com_example_hdrimg2_HDRRenderer
 * Method:    glesResize
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_example_hdrimg2_HDRRenderer_glesResize
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
