/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_hdrimg2_OpenCvJNI */

#ifndef _Included_com_example_hdrimg2_OpenCvJNI
#define _Included_com_example_hdrimg2_OpenCvJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_hdrimg2_OpenCvJNI
 * Method:    process
 * Signature: ([III)[I
 */
JNIEXPORT jintArray JNICALL Java_com_example_hdrimg2_OpenCvJNI_process
  (JNIEnv *, jobject, jintArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
