/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class NativeAdd */

#ifndef _Included_NativeAdd
#define _Included_NativeAdd
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     NativeAdd
 * Method:    add
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_NativeAdd_add
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
